"""PADS ASCII generator for schematic Part Type and PCB Decal."""

from ..models import DevicePinout, PackageSpec, ClassifiedPin
from ..classifier import partition_for_symbol
from .base import Generator


# PADS Logic pin-type codes for Part Type ASCII files.
_PADS_PIN_TYPE = {
    "INPUT": "IN",
    "OUTPUT": "OUT",
    "BIDIRECTIONAL": "BI",
    "POWER": "PWR",
    "GROUND": "GND",
    "PASSIVE": "NC",
    "NC": "NC",
}


class PadsGenerator(Generator):
    @property
    def name(self) -> str:
        return "PADS"

    def generate_symbol(
        self,
        device: DevicePinout,
        pins: list[ClassifiedPin],
        spec: PackageSpec,
    ) -> dict[str, str]:
        sections = partition_for_symbol(pins)
        part_name = device.full_name.upper()

        lines = [
            "*PADS-LIBRARY-PART-TYPES-ASCII*",
            "",
            f"{part_name}\t{device.package_code.upper()}\t{device.total_pins}",
            "",
            "*REMARK*",
            f"* Generated by polylibs for {device.full_name}",
            "",
            "*PIN*",
        ]

        for sec in sections:
            lines.append(f"*SEC {sec.name}")
            for cp in sec.pins:
                direction = _PADS_PIN_TYPE.get(cp.direction.value, "NC")
                lines.append(f"{cp.record.ball_id}\t{cp.record.pin_name}\t{direction}")

        lines.append("")
        lines.append("*END*")

        return {f"{device.full_name.upper()}_part.txt": "\n".join(lines)}

    def generate_footprint(
        self,
        device: DevicePinout,
        spec: PackageSpec,
        coords: dict[str, tuple[float, float]],
    ) -> dict[str, str]:
        pkg_name = device.package_code.upper()
        pad_name = f"BGA_{spec.pitch_mm:.2f}MM_{spec.pad_diameter_mm:.2f}MM"

        lines = [
            "*PADS-LIBRARY-DECALS-ASCII*",
            "",
            f"{pkg_name}",
            f"{len(coords)}",
            "",
            "*REMARK*",
            f"* Generated by polylibs for {device.full_name}",
            "",
            "*PADS*",
        ]

        for ball_id, (x, y) in sorted(coords.items()):
            lines.append(f"{ball_id}\t{pad_name}\t{x:.4f}\t{y:.4f}")

        # Silkscreen outline
        half_x = spec.body_size_x / 2.0 + 0.5
        half_y = spec.body_size_y / 2.0 + 0.5
        lines.append("")
        lines.append("*LINES*")
        lines.append(f"{-half_x:.2f}\t{-half_y:.2f}\t{half_x:.2f}\t{-half_y:.2f}\t0.15")
        lines.append(f"{half_x:.2f}\t{-half_y:.2f}\t{half_x:.2f}\t{half_y:.2f}\t0.15")
        lines.append(f"{half_x:.2f}\t{half_y:.2f}\t{-half_x:.2f}\t{half_y:.2f}\t0.15")
        lines.append(f"{-half_x:.2f}\t{half_y:.2f}\t{-half_x:.2f}\t{-half_y:.2f}\t0.15")

        lines.append("")
        lines.append("*END*")

        return {f"{pkg_name}.dec": "\n".join(lines)}
